source "https://rubygems.org"

gemspec

group :development, :test do
  gem "dotenv", "~> 2.8" # Add dotenv for local environment variables
end

group :test do
  gem "rack-test", "~> 2.1.0"
  gem "rspec", "~> 3.13.1"
  gem "simplecov", "~> 0.22.0", require: false
  gem "webmock", "~> 3.18"
end
